function init(self)
	msg.post("#camera", "acquire_camera_focus")
	self.initial_position = go.get_position()
end

function final(self)
	msg.post("#camera", "release_camera_focus")
end

function update(self, dt)
	--
	-- limit the vertical position so that we don't scroll below the original position
	-- there's no point looking at a lot of ground
	--
	local pos = go.get_position()
	pos.y = math.max(pos.y, self.initial_position.y)
	go.set_position(pos)
end
